name = "game-dev-diary"
type = "javascript"

account_id = "ecd90052f556d3cb79c293ce5ab5f3c4"
workers_dev = true
route = "api.gamediary.dev/*"
zone_id = "ac5586061a44553ab1e9757945b4adcb"
compatibility_date = "2021-12-24"

[build]
command = "mkdir -p target && deno bundle src/worker.ts target/worker.js"

[build.upload]
format = "modules"
dir = "./target"
main = "./worker.js"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[triggers]
# Run every day at 00:00
crons = ["0 0 * * *"]

[vars]
ACCOUNT_ID = "ecd90052f556d3cb79c293ce5ab5f3c4"
PROJECT_NAME = "game-dev-diary"
DISCORD_WEBHOOK_ID = "924620329161216051"

# [secrets]
# EMAIL
# AUTH_KEY
# WEBHOOK_SECRET
# DISCORD_WEBHOOK_TOKEN
