name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: Linting files
        run: deno lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: Running tests
        run: deno test --lock=lock.test.json tests/

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: Checking format
        run: deno fmt --check

  deploy:
    name: Deploy worker
    runs-on: ubuntu-latest
    needs: [lint, test, format]
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1.0.0
        with:
          deno-version: v1.x

      - name: Reload cache
        run: deno cache --reload --lock=lock.json src/worker.ts

      - name: Install Wrangler
        run: npm i -g @cloudflare/wrangler

      - name: Publish
        run: wrangler publish
        env:
           CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
